#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=commands/shared/all.sh
source "${DXC_HOME}/shared/all.sh"
# shellcheck source=commands/core/delete.sh
source "${DXC_HOME}/core/delete.sh"


dx::log::info 'Do you really want to run this command? It can delete some Docker resources. Be careful. [y/n]'
read -e -r confirmation

if [ "${confirmation}" = 'y' ] || [ "${confirmation}" = 'yes' ]; then
  dx::delete
fi
