#!/usr/bin/env bash

set -euo pipefail

source "${DXC_HOME}/shared/all.sh"
source "${DXC_HOME}/core/delete.sh"

#?? Remove one or more resources
##?
##?
##? Usage:
##?     delete
##?
##? Examples:
##?     delete

dx::delete
