#!/usr/bin/env bash

set -euo pipefail

source "${DXC_HOME}/shared/all.sh"
source "${DXC_HOME}/core/exec.sh"

#?? Execute custom commands in a running container
##?
##?
##? Usage:
##?     exec
##?
##? Examples:
##?     exec

dx::exec
