#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=commands/shared/all.sh
source "${DXC_HOME}/shared/all.sh"
# shellcheck source=commands/core/exec.sh
source "${DXC_HOME}/core/exec.sh"

dx::exec
