#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=commands/shared/all.sh
source "${DXC_HOME}/shared/all.sh"
# shellcheck source=commands/core/ls.sh
source "${DXC_HOME}/core/ls.sh"

#?? List all resources
##?
##?
##? Usage:
##?     ls
##?
##? Examples:
##?     ls

dx::list
