#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=commands/shared/all.sh
source "${DXC_HOME}/shared/all.sh"
# shellcheck source=commands/core/pid.sh
source "${DXC_HOME}/core/pid.sh"

dx::pid
