#!/usr/bin/env bash

set -euo pipefail

# shellcheck source=commands/shared/all.sh
source "${DXC_HOME}/shared/all.sh"
# shellcheck source=commands/core/prune.sh
source "${DXC_HOME}/core/prune.sh"

readonly resource_filter="${1:-}"

dx::assert::non_empty "${resource_filter}" 'The prune command requires a resource filter.'

if ${DX_CONFIRMATION_REQUIRED:-true}; then
  dx::log::info 'Do you really want to delete the Docker resources with this filter? Be careful. [y/n]'
  read -e -r confirmation
fi

if ! "${DX_CONFIRMATION_REQUIRED:-true}" \
  || [ "${confirmation:-'n'}" = 'y' ] \
  || [ "${confirmation:-'n'}" = 'yes' ]; then
  case "${resource_filter}" in
    'all') dx::remove_all ;;
    'dirt') dx::clean_up_dirt ;;
    'containers') dx::remove_all_containers ;;
    'images') dx::remove_images ;;
    'volumes') dx::remove_volumes ;;
    'networks') dx::remove_networks ;;
    *) dx::log::errexit "Invalid resource filter (${resource_filter})" ;;
  esac
fi
