name: Checks
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Formatting shell script code (using shfmt)
        uses: bltavares/actions/shfmt@master
        env:
          GITHUB_TOKEN: ${{ secrets.DX_GITHUB_TOKEN }}
          SHFMT_ARGS: -i 2 -ci -bn
        with:
          args: autofix
      - name: Checking shell script code issues (using shellcheck)
        uses: zbeekman/ShellCheck-Linter-Action@v1.0.1
